# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Publish Release

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual execution'

  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release Artifacts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout Code      
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Test and Build
      run: |
        go test -v ./...
        mkdir -p ./dist
        CGO_ENABLED=0 go build -o ./dist/mcpd.x86_64 -ldflags="-s -w -extldflags '-static'" -v ./cmd/mcpd
        ls -la ./dist
        
    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
          files: ./dist/mcpd.x86_64
          draft: false
          prerelease: false
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

